main: me.timlampen.lcc.Main
version: 1.0
name: LCC
depend: [Vault]
commands:
  lcc:
    description: Base command for all LCC related commands
  togglechat:
    description: Base command for all LCC related commands